'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property Customer_Name As String
    Public Property Customer_Phone As String
    Public Property Customer_Email As String
    Public Property Bill_No As String
    Public Property Payment As String

    Public Overridable Property Sales As ICollection(Of Sale) = New HashSet(Of Sale)

End Class
