'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mobile
    Public Property MobId As Integer
    Public Property Brand As String
    Public Property Model As String
    Public Property Storage As String
    Public Property Ram As String
    Public Property Back As String
    Public Property Front As String
    Public Property Quantity As Integer
    Public Property img As Byte()
    Public Property Price As Nullable(Of Decimal)
    Public Property RegId As Nullable(Of Integer)

    Public Overridable Property Sales As ICollection(Of Sale) = New HashSet(Of Sale)
    Public Overridable Property Signup As Signup

End Class
