
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute("6403e30f-0f69-47a4-926d-46436eeea4c8")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("Database2Model", "FK_Bill_No", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Customer), "Sales", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Sale), True)>
<Assembly: EdmRelationshipAttribute("Database2Model", "FK_MobId", "Mobile", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Mobile), "Sales", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Sale), True)>
<Assembly: EdmRelationshipAttribute("Database2Model", "FK_RegId", "Signup", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Signup), "Mobile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Mobile), True)>
<Assembly: EdmRelationshipAttribute("Database2Model", "FK_RegId_S", "Signup", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Signup), "Sales", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Sale), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class Database2Entities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new Database2Entities object using the connection string found in the 'Database2Entities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Database2Entities", "Database2Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Database2Entities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Database2Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new Database2Entities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Database2Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Customers() As ObjectSet(Of Customer)
        Get
            If (_Customers Is Nothing) Then
                _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
            End If
            Return _Customers
        End Get
    End Property

    Private _Customers As ObjectSet(Of Customer)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Mobiles() As ObjectSet(Of Mobile)
        Get
            If (_Mobiles Is Nothing) Then
                _Mobiles = MyBase.CreateObjectSet(Of Mobile)("Mobiles")
            End If
            Return _Mobiles
        End Get
    End Property

    Private _Mobiles As ObjectSet(Of Mobile)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Outlets() As ObjectSet(Of Outlet)
        Get
            If (_Outlets Is Nothing) Then
                _Outlets = MyBase.CreateObjectSet(Of Outlet)("Outlets")
            End If
            Return _Outlets
        End Get
    End Property

    Private _Outlets As ObjectSet(Of Outlet)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Sales() As ObjectSet(Of Sale)
        Get
            If (_Sales Is Nothing) Then
                _Sales = MyBase.CreateObjectSet(Of Sale)("Sales")
            End If
            Return _Sales
        End Get
    End Property

    Private _Sales As ObjectSet(Of Sale)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Signups() As ObjectSet(Of Signup)
        Get
            If (_Signups Is Nothing) Then
                _Signups = MyBase.CreateObjectSet(Of Signup)("Signups")
            End If
            Return _Signups
        End Get
    End Property

    Private _Signups As ObjectSet(Of Signup)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCustomers(ByVal customer As Customer)
        MyBase.AddObject("Customers", customer)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Mobiles EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMobiles(ByVal mobile As Mobile)
        MyBase.AddObject("Mobiles", mobile)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Outlets EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOutlets(ByVal outlet As Outlet)
        MyBase.AddObject("Outlets", outlet)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Sales EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSales(ByVal sale As Sale)
        MyBase.AddObject("Sales", sale)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Signups EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSignups(ByVal signup As Signup)
        MyBase.AddObject("Signups", signup)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Customer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Customer
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Customer object.
    ''' </summary>
    ''' <param name="bill_No">Initial value of the Bill_No property.</param>
    Public Shared Function CreateCustomer(bill_No As Global.System.String) As Customer
        Dim customer as Customer = New Customer
        customer.Bill_No = bill_No
        Return customer
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Customer_Name() As Global.System.String
        Get
            Return _Customer_Name
        End Get
        Set
            OnCustomer_NameChanging(value)
            ReportPropertyChanging("Customer_Name")
            _Customer_Name = StructuralObject.SetValidValue(value, true, "Customer_Name")
            ReportPropertyChanged("Customer_Name")
            OnCustomer_NameChanged()
        End Set
    End Property

    Private _Customer_Name As Global.System.String
    Private Partial Sub OnCustomer_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomer_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Customer_Phone() As Global.System.String
        Get
            Return _Customer_Phone
        End Get
        Set
            OnCustomer_PhoneChanging(value)
            ReportPropertyChanging("Customer_Phone")
            _Customer_Phone = StructuralObject.SetValidValue(value, true, "Customer_Phone")
            ReportPropertyChanged("Customer_Phone")
            OnCustomer_PhoneChanged()
        End Set
    End Property

    Private _Customer_Phone As Global.System.String
    Private Partial Sub OnCustomer_PhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomer_PhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Customer_Email() As Global.System.String
        Get
            Return _Customer_Email
        End Get
        Set
            OnCustomer_EmailChanging(value)
            ReportPropertyChanging("Customer_Email")
            _Customer_Email = StructuralObject.SetValidValue(value, true, "Customer_Email")
            ReportPropertyChanged("Customer_Email")
            OnCustomer_EmailChanged()
        End Set
    End Property

    Private _Customer_Email As Global.System.String
    Private Partial Sub OnCustomer_EmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCustomer_EmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Bill_No() As Global.System.String
        Get
            Return _Bill_No
        End Get
        Set
            If (_Bill_No <> Value) Then
                OnBill_NoChanging(value)
                ReportPropertyChanging("Bill_No")
                _Bill_No = StructuralObject.SetValidValue(value, false, "Bill_No")
                ReportPropertyChanged("Bill_No")
                OnBill_NoChanged()
            End If
        End Set
    End Property

    Private _Bill_No As Global.System.String
    Private Partial Sub OnBill_NoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBill_NoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Payment() As Global.System.String
        Get
            Return _Payment
        End Get
        Set
            OnPaymentChanging(value)
            ReportPropertyChanging("Payment")
            _Payment = StructuralObject.SetValidValue(value, true, "Payment")
            ReportPropertyChanged("Payment")
            OnPaymentChanged()
        End Set
    End Property

    Private _Payment As Global.System.String
    Private Partial Sub OnPaymentChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPaymentChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_Bill_No", "Sales")>
     Public Property Sales() As EntityCollection(Of Sale)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Sale)("Database2Model.FK_Bill_No", "Sales")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Sale)("Database2Model.FK_Bill_No", "Sales", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Mobile")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Mobile
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Mobile object.
    ''' </summary>
    ''' <param name="mobId">Initial value of the MobId property.</param>
    ''' <param name="brand">Initial value of the Brand property.</param>
    ''' <param name="model">Initial value of the Model property.</param>
    ''' <param name="storage">Initial value of the Storage property.</param>
    ''' <param name="ram">Initial value of the Ram property.</param>
    ''' <param name="back">Initial value of the Back property.</param>
    ''' <param name="front">Initial value of the Front property.</param>
    ''' <param name="quantity">Initial value of the Quantity property.</param>
    Public Shared Function CreateMobile(mobId As Global.System.Int32, brand As Global.System.String, model As Global.System.String, storage As Global.System.String, ram As Global.System.String, back As Global.System.String, front As Global.System.String, quantity As Global.System.Int32) As Mobile
        Dim mobile as Mobile = New Mobile
        mobile.MobId = mobId
        mobile.Brand = brand
        mobile.Model = model
        mobile.Storage = storage
        mobile.Ram = ram
        mobile.Back = back
        mobile.Front = front
        mobile.Quantity = quantity
        Return mobile
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MobId() As Global.System.Int32
        Get
            Return _MobId
        End Get
        Set
            If (_MobId <> Value) Then
                OnMobIdChanging(value)
                ReportPropertyChanging("MobId")
                _MobId = StructuralObject.SetValidValue(value, "MobId")
                ReportPropertyChanged("MobId")
                OnMobIdChanged()
            End If
        End Set
    End Property

    Private _MobId As Global.System.Int32
    Private Partial Sub OnMobIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnMobIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Brand() As Global.System.String
        Get
            Return _Brand
        End Get
        Set
            OnBrandChanging(value)
            ReportPropertyChanging("Brand")
            _Brand = StructuralObject.SetValidValue(value, false, "Brand")
            ReportPropertyChanged("Brand")
            OnBrandChanged()
        End Set
    End Property

    Private _Brand As Global.System.String
    Private Partial Sub OnBrandChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBrandChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Model() As Global.System.String
        Get
            Return _Model
        End Get
        Set
            OnModelChanging(value)
            ReportPropertyChanging("Model")
            _Model = StructuralObject.SetValidValue(value, false, "Model")
            ReportPropertyChanged("Model")
            OnModelChanged()
        End Set
    End Property

    Private _Model As Global.System.String
    Private Partial Sub OnModelChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Storage() As Global.System.String
        Get
            Return _Storage
        End Get
        Set
            OnStorageChanging(value)
            ReportPropertyChanging("Storage")
            _Storage = StructuralObject.SetValidValue(value, false, "Storage")
            ReportPropertyChanged("Storage")
            OnStorageChanged()
        End Set
    End Property

    Private _Storage As Global.System.String
    Private Partial Sub OnStorageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStorageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Ram() As Global.System.String
        Get
            Return _Ram
        End Get
        Set
            OnRamChanging(value)
            ReportPropertyChanging("Ram")
            _Ram = StructuralObject.SetValidValue(value, false, "Ram")
            ReportPropertyChanged("Ram")
            OnRamChanged()
        End Set
    End Property

    Private _Ram As Global.System.String
    Private Partial Sub OnRamChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRamChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Back() As Global.System.String
        Get
            Return _Back
        End Get
        Set
            OnBackChanging(value)
            ReportPropertyChanging("Back")
            _Back = StructuralObject.SetValidValue(value, false, "Back")
            ReportPropertyChanged("Back")
            OnBackChanged()
        End Set
    End Property

    Private _Back As Global.System.String
    Private Partial Sub OnBackChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBackChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Front() As Global.System.String
        Get
            Return _Front
        End Get
        Set
            OnFrontChanging(value)
            ReportPropertyChanging("Front")
            _Front = StructuralObject.SetValidValue(value, false, "Front")
            ReportPropertyChanged("Front")
            OnFrontChanged()
        End Set
    End Property

    Private _Front As Global.System.String
    Private Partial Sub OnFrontChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFrontChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Quantity() As Global.System.Int32
        Get
            Return _Quantity
        End Get
        Set
            OnQuantityChanging(value)
            ReportPropertyChanging("Quantity")
            _Quantity = StructuralObject.SetValidValue(value, "Quantity")
            ReportPropertyChanged("Quantity")
            OnQuantityChanged()
        End Set
    End Property

    Private _Quantity As Global.System.Int32
    Private Partial Sub OnQuantityChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnQuantityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property img() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_img)
        End Get
        Set
            OnimgChanging(value)
            ReportPropertyChanging("img")
            _img = StructuralObject.SetValidValue(value, true, "img")
            ReportPropertyChanged("img")
            OnimgChanged()
        End Set
    End Property

    Private _img As Global.System.Byte()
    Private Partial Sub OnimgChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnimgChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Price() As Nullable(Of Global.System.Decimal)
        Get
            Return _Price
        End Get
        Set
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value, "Price")
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property

    Private _Price As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RegId() As Nullable(Of Global.System.Int32)
        Get
            Return _RegId
        End Get
        Set
            OnRegIdChanging(value)
            ReportPropertyChanging("RegId")
            _RegId = StructuralObject.SetValidValue(value, "RegId")
            ReportPropertyChanged("RegId")
            OnRegIdChanged()
        End Set
    End Property

    Private _RegId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnRegIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnRegIdChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_MobId", "Sales")>
     Public Property Sales() As EntityCollection(Of Sale)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Sale)("Database2Model.FK_MobId", "Sales")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Sale)("Database2Model.FK_MobId", "Sales", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_RegId", "Signup")>
    Public Property Signup() As Signup
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Signup)("Database2Model.FK_RegId", "Signup").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Signup)("Database2Model.FK_RegId", "Signup").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SignupReference() As EntityReference(Of Signup)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Signup)("Database2Model.FK_RegId", "Signup")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Signup)("Database2Model.FK_RegId", "Signup", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Outlet")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Outlet
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Outlet object.
    ''' </summary>
    ''' <param name="oId">Initial value of the OId property.</param>
    Public Shared Function CreateOutlet(oId As Global.System.Int32) As Outlet
        Dim outlet as Outlet = New Outlet
        outlet.OId = oId
        Return outlet
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OId() As Global.System.Int32
        Get
            Return _OId
        End Get
        Set
            If (_OId <> Value) Then
                OnOIdChanging(value)
                ReportPropertyChanging("OId")
                _OId = StructuralObject.SetValidValue(value, "OId")
                ReportPropertyChanged("OId")
                OnOIdChanged()
            End If
        End Set
    End Property

    Private _OId As Global.System.Int32
    Private Partial Sub OnOIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnOIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, true, "name")
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Locality() As Global.System.String
        Get
            Return _Locality
        End Get
        Set
            OnLocalityChanging(value)
            ReportPropertyChanging("Locality")
            _Locality = StructuralObject.SetValidValue(value, true, "Locality")
            ReportPropertyChanged("Locality")
            OnLocalityChanged()
        End Set
    End Property

    Private _Locality As Global.System.String
    Private Partial Sub OnLocalityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLocalityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property city() As Global.System.String
        Get
            Return _city
        End Get
        Set
            OncityChanging(value)
            ReportPropertyChanging("city")
            _city = StructuralObject.SetValidValue(value, true, "city")
            ReportPropertyChanged("city")
            OncityChanged()
        End Set
    End Property

    Private _city As Global.System.String
    Private Partial Sub OncityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OncityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property pincode() As Global.System.String
        Get
            Return _pincode
        End Get
        Set
            OnpincodeChanging(value)
            ReportPropertyChanging("pincode")
            _pincode = StructuralObject.SetValidValue(value, true, "pincode")
            ReportPropertyChanged("pincode")
            OnpincodeChanged()
        End Set
    End Property

    Private _pincode As Global.System.String
    Private Partial Sub OnpincodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpincodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property state() As Global.System.String
        Get
            Return _state
        End Get
        Set
            OnstateChanging(value)
            ReportPropertyChanging("state")
            _state = StructuralObject.SetValidValue(value, true, "state")
            ReportPropertyChanged("state")
            OnstateChanged()
        End Set
    End Property

    Private _state As Global.System.String
    Private Partial Sub OnstateChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property pno() As Global.System.String
        Get
            Return _pno
        End Get
        Set
            OnpnoChanging(value)
            ReportPropertyChanging("pno")
            _pno = StructuralObject.SetValidValue(value, true, "pno")
            ReportPropertyChanged("pno")
            OnpnoChanged()
        End Set
    End Property

    Private _pno As Global.System.String
    Private Partial Sub OnpnoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpnoChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Sale")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Sale
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Sale object.
    ''' </summary>
    ''' <param name="model">Initial value of the Model property.</param>
    ''' <param name="price_">Initial value of the Price_ property.</param>
    ''' <param name="total">Initial value of the Total property.</param>
    ''' <param name="p_date">Initial value of the P_date property.</param>
    ''' <param name="bill_No">Initial value of the Bill_No property.</param>
    Public Shared Function CreateSale(model As Global.System.String, price_ As Global.System.Decimal, total As Global.System.String, p_date As Global.System.DateTime, bill_No As Global.System.String) As Sale
        Dim sale as Sale = New Sale
        sale.Model = model
        sale.Price_ = price_
        sale.Total = total
        sale.P_date = p_date
        sale.Bill_No = bill_No
        Return sale
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Brand() As Global.System.String
        Get
            Return _Brand
        End Get
        Set
            OnBrandChanging(value)
            ReportPropertyChanging("Brand")
            _Brand = StructuralObject.SetValidValue(value, true, "Brand")
            ReportPropertyChanged("Brand")
            OnBrandChanged()
        End Set
    End Property

    Private _Brand As Global.System.String
    Private Partial Sub OnBrandChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBrandChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Model() As Global.System.String
        Get
            Return _Model
        End Get
        Set
            If (_Model <> Value) Then
                OnModelChanging(value)
                ReportPropertyChanging("Model")
                _Model = StructuralObject.SetValidValue(value, false, "Model")
                ReportPropertyChanged("Model")
                OnModelChanged()
            End If
        End Set
    End Property

    Private _Model As Global.System.String
    Private Partial Sub OnModelChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Price_() As Global.System.Decimal
        Get
            Return _Price_
        End Get
        Set
            If (_Price_ <> Value) Then
                OnPrice_Changing(value)
                ReportPropertyChanging("Price_")
                _Price_ = StructuralObject.SetValidValue(value, "Price_")
                ReportPropertyChanged("Price_")
                OnPrice_Changed()
            End If
        End Set
    End Property

    Private _Price_ As Global.System.Decimal
    Private Partial Sub OnPrice_Changing(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPrice_Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Qty() As Nullable(Of Global.System.Int32)
        Get
            Return _Qty
        End Get
        Set
            OnQtyChanging(value)
            ReportPropertyChanging("Qty")
            _Qty = StructuralObject.SetValidValue(value, "Qty")
            ReportPropertyChanged("Qty")
            OnQtyChanged()
        End Set
    End Property

    Private _Qty As Nullable(Of Global.System.Int32)
    Private Partial Sub OnQtyChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnQtyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Total() As Global.System.String
        Get
            Return _Total
        End Get
        Set
            If (_Total <> Value) Then
                OnTotalChanging(value)
                ReportPropertyChanging("Total")
                _Total = StructuralObject.SetValidValue(value, false, "Total")
                ReportPropertyChanged("Total")
                OnTotalChanged()
            End If
        End Set
    End Property

    Private _Total As Global.System.String
    Private Partial Sub OnTotalChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTotalChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property P_date() As Global.System.DateTime
        Get
            Return _P_date
        End Get
        Set
            If (_P_date <> Value) Then
                OnP_dateChanging(value)
                ReportPropertyChanging("P_date")
                _P_date = StructuralObject.SetValidValue(value, "P_date")
                ReportPropertyChanged("P_date")
                OnP_dateChanged()
            End If
        End Set
    End Property

    Private _P_date As Global.System.DateTime
    Private Partial Sub OnP_dateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnP_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Bill_No() As Global.System.String
        Get
            Return _Bill_No
        End Get
        Set
            If (_Bill_No <> Value) Then
                OnBill_NoChanging(value)
                ReportPropertyChanging("Bill_No")
                _Bill_No = StructuralObject.SetValidValue(value, false, "Bill_No")
                ReportPropertyChanged("Bill_No")
                OnBill_NoChanged()
            End If
        End Set
    End Property

    Private _Bill_No As Global.System.String
    Private Partial Sub OnBill_NoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBill_NoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RegId() As Nullable(Of Global.System.Int32)
        Get
            Return _RegId
        End Get
        Set
            OnRegIdChanging(value)
            ReportPropertyChanging("RegId")
            _RegId = StructuralObject.SetValidValue(value, "RegId")
            ReportPropertyChanged("RegId")
            OnRegIdChanged()
        End Set
    End Property

    Private _RegId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnRegIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnRegIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MobId() As Nullable(Of Global.System.Int32)
        Get
            Return _MobId
        End Get
        Set
            OnMobIdChanging(value)
            ReportPropertyChanging("MobId")
            _MobId = StructuralObject.SetValidValue(value, "MobId")
            ReportPropertyChanged("MobId")
            OnMobIdChanged()
        End Set
    End Property

    Private _MobId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnMobIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnMobIdChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_Bill_No", "Customer")>
    Public Property Customer() As Customer
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("Database2Model.FK_Bill_No", "Customer").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("Database2Model.FK_Bill_No", "Customer").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CustomerReference() As EntityReference(Of Customer)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("Database2Model.FK_Bill_No", "Customer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("Database2Model.FK_Bill_No", "Customer", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_MobId", "Mobile")>
    Public Property Mobile() As Mobile
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mobile)("Database2Model.FK_MobId", "Mobile").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mobile)("Database2Model.FK_MobId", "Mobile").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MobileReference() As EntityReference(Of Mobile)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mobile)("Database2Model.FK_MobId", "Mobile")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Mobile)("Database2Model.FK_MobId", "Mobile", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_RegId_S", "Signup")>
    Public Property Signup() As Signup
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Signup)("Database2Model.FK_RegId_S", "Signup").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Signup)("Database2Model.FK_RegId_S", "Signup").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SignupReference() As EntityReference(Of Signup)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Signup)("Database2Model.FK_RegId_S", "Signup")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Signup)("Database2Model.FK_RegId_S", "Signup", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Database2Model", Name:="Signup")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Signup
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Signup object.
    ''' </summary>
    ''' <param name="regId">Initial value of the RegId property.</param>
    ''' <param name="first_Name">Initial value of the First_Name property.</param>
    ''' <param name="last_Name">Initial value of the Last_Name property.</param>
    ''' <param name="gender">Initial value of the Gender property.</param>
    ''' <param name="phone_Number">Initial value of the Phone_Number property.</param>
    ''' <param name="username">Initial value of the Username property.</param>
    ''' <param name="password">Initial value of the Password property.</param>
    ''' <param name="confirm_Password">Initial value of the Confirm_Password property.</param>
    Public Shared Function CreateSignup(regId As Global.System.Int32, first_Name As Global.System.String, last_Name As Global.System.String, gender As Global.System.String, phone_Number As Global.System.String, username As Global.System.String, password As Global.System.String, confirm_Password As Global.System.String) As Signup
        Dim signup as Signup = New Signup
        signup.RegId = regId
        signup.First_Name = first_Name
        signup.Last_Name = last_Name
        signup.Gender = gender
        signup.Phone_Number = phone_Number
        signup.Username = username
        signup.Password = password
        signup.Confirm_Password = confirm_Password
        Return signup
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RegId() As Global.System.Int32
        Get
            Return _RegId
        End Get
        Set
            If (_RegId <> Value) Then
                OnRegIdChanging(value)
                ReportPropertyChanging("RegId")
                _RegId = StructuralObject.SetValidValue(value, "RegId")
                ReportPropertyChanged("RegId")
                OnRegIdChanged()
            End If
        End Set
    End Property

    Private _RegId As Global.System.Int32
    Private Partial Sub OnRegIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRegIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property First_Name() As Global.System.String
        Get
            Return _First_Name
        End Get
        Set
            OnFirst_NameChanging(value)
            ReportPropertyChanging("First_Name")
            _First_Name = StructuralObject.SetValidValue(value, false, "First_Name")
            ReportPropertyChanged("First_Name")
            OnFirst_NameChanged()
        End Set
    End Property

    Private _First_Name As Global.System.String
    Private Partial Sub OnFirst_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnFirst_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Last_Name() As Global.System.String
        Get
            Return _Last_Name
        End Get
        Set
            OnLast_NameChanging(value)
            ReportPropertyChanging("Last_Name")
            _Last_Name = StructuralObject.SetValidValue(value, false, "Last_Name")
            ReportPropertyChanged("Last_Name")
            OnLast_NameChanged()
        End Set
    End Property

    Private _Last_Name As Global.System.String
    Private Partial Sub OnLast_NameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLast_NameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Gender() As Global.System.String
        Get
            Return _Gender
        End Get
        Set
            OnGenderChanging(value)
            ReportPropertyChanging("Gender")
            _Gender = StructuralObject.SetValidValue(value, false, "Gender")
            ReportPropertyChanged("Gender")
            OnGenderChanged()
        End Set
    End Property

    Private _Gender As Global.System.String
    Private Partial Sub OnGenderChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGenderChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Phone_Number() As Global.System.String
        Get
            Return _Phone_Number
        End Get
        Set
            OnPhone_NumberChanging(value)
            ReportPropertyChanging("Phone_Number")
            _Phone_Number = StructuralObject.SetValidValue(value, false, "Phone_Number")
            ReportPropertyChanged("Phone_Number")
            OnPhone_NumberChanged()
        End Set
    End Property

    Private _Phone_Number As Global.System.String
    Private Partial Sub OnPhone_NumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPhone_NumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Username() As Global.System.String
        Get
            Return _Username
        End Get
        Set
            OnUsernameChanging(value)
            ReportPropertyChanging("Username")
            _Username = StructuralObject.SetValidValue(value, false, "Username")
            ReportPropertyChanged("Username")
            OnUsernameChanged()
        End Set
    End Property

    Private _Username As Global.System.String
    Private Partial Sub OnUsernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUsernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, false, "Password")
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Confirm_Password() As Global.System.String
        Get
            Return _Confirm_Password
        End Get
        Set
            OnConfirm_PasswordChanging(value)
            ReportPropertyChanging("Confirm_Password")
            _Confirm_Password = StructuralObject.SetValidValue(value, false, "Confirm_Password")
            ReportPropertyChanged("Confirm_Password")
            OnConfirm_PasswordChanged()
        End Set
    End Property

    Private _Confirm_Password As Global.System.String
    Private Partial Sub OnConfirm_PasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnConfirm_PasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Usertype() As Global.System.String
        Get
            Return _Usertype
        End Get
        Set
            OnUsertypeChanging(value)
            ReportPropertyChanging("Usertype")
            _Usertype = StructuralObject.SetValidValue(value, true, "Usertype")
            ReportPropertyChanged("Usertype")
            OnUsertypeChanged()
        End Set
    End Property

    Private _Usertype As Global.System.String
    Private Partial Sub OnUsertypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUsertypeChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_RegId", "Mobile")>
     Public Property Mobiles() As EntityCollection(Of Mobile)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Mobile)("Database2Model.FK_RegId", "Mobile")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Mobile)("Database2Model.FK_RegId", "Mobile", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Database2Model", "FK_RegId_S", "Sales")>
     Public Property Sales() As EntityCollection(Of Sale)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Sale)("Database2Model.FK_RegId_S", "Sales")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Sale)("Database2Model.FK_RegId_S", "Sales", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region

