'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Database2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Database2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Customers() As DbSet(Of Customer)
    Public Property Mobiles() As DbSet(Of Mobile)
    Public Property Outlets() As DbSet(Of Outlet)
    Public Property Sales() As DbSet(Of Sale)
    Public Property Signups() As DbSet(Of Signup)

End Class
