'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sale
    Public Property Brand As String
    Public Property Model As String
    Public Property Price_ As Decimal
    Public Property Qty As Nullable(Of Integer)
    Public Property Total As String
    Public Property P_date As Date
    Public Property Bill_No As String
    Public Property RegId As Nullable(Of Integer)
    Public Property MobId As Nullable(Of Integer)

    Public Overridable Property Customer As Customer
    Public Overridable Property Mobile As Mobile
    Public Overridable Property Signup As Signup

End Class
