'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Signup
    Public Property RegId As Integer
    Public Property First_Name As String
    Public Property Last_Name As String
    Public Property Gender As String
    Public Property Phone_Number As String
    Public Property Username As String
    Public Property Password As String
    Public Property Confirm_Password As String
    Public Property Usertype As String

    Public Overridable Property Mobiles As ICollection(Of Mobile) = New HashSet(Of Mobile)
    Public Overridable Property Sales As ICollection(Of Sale) = New HashSet(Of Sale)

End Class
